POST https://node-basic-hrlf.onrender.com/videos
Content-Type: application/json

{
    "title":  "Video sobre formula 1",
    "description": "Esse é o primeiro",
    "duration": 190
}

###

GET https://node-basic-hrlf.onrender.com/videos

###

PUT https://node-basic-hrlf.onrender.com/videos/eea0fd0f-1be1-456d-9fe0-4b8bb93ea436
Content-Type: application/json

{
    "title":  "Video sobre carros",
    "description": "Esse é o primeiro mudado",
    "duration": 190
}

###

DELETE  https://node-basic-hrlf.onrender.com/videos/f84c4552-3e6b-4b7a-a29f-76eacfb5d68e


